import rooms from '../db/rooms.ts';
import stringifyData from '../utils/stringifyData.ts';
import type WebSocket from 'ws';

export const createGame = (indexRoom: string | number) => {
	const room = rooms.get(indexRoom)!;

	if (room.roomUsers.length < 2) {
		return;
	}

	const [player1, player2] = room.roomUsers;

	const data = {
		idGame: 0,
		idPlayer: 0 /* generated by server id for player in the game session, not enemy (unique id for every player) */,
	};

	const response = stringifyData({
		type: 'create_game', //send for both players in the room, after they are connected to the room
		data,
		id: 0,
	});
};
